name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create config file
        run: |
          echo "var APP_CONFIG = {" > congfig.js
          echo "  githubToken: '${{ secrets.GH_TOKEN }}'," >> congfig.js
          echo "  groqToken: '${{ secrets.GROQ_TOKEN }}'," >> congfig.js
          echo "  mistralToken: '${{ secrets.MISTRAL_TOKEN }}'," >> congfig.js
          echo "  version: '5.0'" >> congfig.js
          echo "};" >> congfig.js
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
